openapi: 3.0.0
servers:
  - description: Skate Directory
    url: http://localhost:31667
info:
  description: SPA for skateboarding local sites
  version: 0.0.1
  license: {name: MIT}
  title: Skate Directory
  contact: {name: Eric}
paths:
  /skate-slc:
    post:
      summary: 
      description: 
      parameters:
        - body: 
          in: 
          description:
          required: 
          schema:
            type: object
      responses:
        '200':
          description: 
          content:
            application/json:
              schema:
                type: object
        '400':
          description: bad request
